### PR TITLE
Add SBoudrias ama!

### PR DESCRIPTION
**Pull request by SBoudrias**
Joining the party!

### CODE REVIEW

**Comment by sindresorhus** [comment]
Woot! :D

**Comment by sindresorhus** [comment]
You need to enable the issue tracker btw.

**Comment by SBoudrias** [comment]
Dear Sindre, it is now enabled! (forgot about forking issues)

**Comment by sindresorhus** [comment]
Hey. Want to ask you a favor. Would be cool if you could ask some questions on the other AMAs in the list (not my AMA). I think AMAs are a great opportunity to learn from each other. Asking a question is also a good way to encourage receiving one ;)

For inspiration of what to ask, you could take a look at the questions in some other AMAs, like:
https://github.com/passy/ama/issues?q=
https://github.com/sebmck/ama/issues?q=
https://github.com/wesbos/ama/issues?q=
https://github.com/sindresorhus/ama/issues?q=

**Pull request merged**
