### PR TITLE
Add Maxime Thirouin

### PR DESCRIPTION
**Pull request by MoOx**
Because it's fun :)
Thanks for the idea.

### CODE REVIEW

**Comment by arthurvr** [comment]
Welcome!

**Comment by sindresorhus** [comment]
Hey. Want to ask you a favor. Would be cool if you could ask some questions on the other AMAs in the list (not my AMA). I think AMAs are a great opportunity to learn from each other. Asking a question is also a good way to encourage receiving one ;)

For inspiration of what to ask, you could take a look at the questions in some other AMAs, like:
https://github.com/passy/ama/issues?q=
https://github.com/sebmck/ama/issues?q=
https://github.com/wesbos/ama/issues?q=
https://github.com/sindresorhus/ama/issues?q=

**Comment by MoOx** [comment]
I will take time for this. Just added to my todo :)

**Comment by sindresorhus** [comment]
Appreciate it :)

**Pull request merged**
