### PR TITLE
Added Claudio Procida

### PR DESCRIPTION
**Pull request by claudiopro**
Hi @sindresorhus!

### CODE REVIEW

**Comment by arthurvr** [comment]
You forgot to turn on the issues in your repo :)

**Comment by claudiopro** [comment]
@arthurvr ops :blush: Thanks for catching this, done!

**Comment by arthurvr** [comment]
Welcome!

**Comment by claudiopro** [comment]
Thank you!

**Comment by sindresorhus** [comment]
Hey. Want to ask you a favor. Would be cool if you could ask some questions on the other AMAs in the list (not my AMA). I think AMAs are a great opportunity to learn from each other. Asking a question is also a good way to encourage receiving one ;)

For inspiration of what to ask, you could take a look at the questions in some other AMAs, like:
https://github.com/passy/ama/issues?q=
https://github.com/sebmck/ama/issues?q=
https://github.com/wesbos/ama/issues?q=
https://github.com/sindresorhus/ama/issues?q=

**Comment by claudiopro** [comment]
I was actually looking at your past answers and found them very inspirational. It's a great way to get to learn and empathize with each other. It's not always easy to talk to others at conferences and meetups, and these give a glimpse at the person behind the handle.

**Pull request merged**
