### PR TITLE
add Anthony Ramella

### PR DESCRIPTION
**Pull request by byzantony**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Welcome! :)

Would be cool if you could ask some questions on the other AMAs in the list (not my AMA). I think AMAs are a great opportunity to learn from each other. Asking a question is also a good way to encourage receiving one ;)

For inspiration of what to ask, you could take a look at the questions in some other AMAs, like:
https://github.com/passy/ama/issues?q=
https://github.com/sebmck/ama/issues?q=
https://github.com/wesbos/ama/issues?q=

**Comment by sindresorhus** [comment]
You need to enable the issue tracker per: https://github.com/sindresorhus/amas/blob/master/create-ama.md

And your repo description is incorrect.

**Comment by sindresorhus** [comment]
The readme needs to be updated too.

**Comment by byzantony** [comment]
What on the readme needs to be updated? I changed the repo description and
enabled issue tracker. Thanks

On Fri, Nov 13, 2015 at 12:11 PM, Sindre Sorhus notifications@github.com
wrote:

> The readme needs to be updated too.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sindresorhus/amas/pull/103#issuecomment-156490932.

## 

Anthony Ramella, B.A.

**Comment by sindresorhus** [comment]
No, you did it in the wrong repo.

This is what's linked and where you should have done all the changes: https://github.com/tonyynot/ama

**Comment by byzantony** [comment]
fixed. sorry about that and thanks for your help!

**Pull request closed without merging**
