### PR TITLE
Add FutoIn organization AMA link

### PR DESCRIPTION
**Pull request by andvgal**

### CODE REVIEW

**Comment by sindresorhus** [comment]
It's not really clear what FutoIn is. It's not explained anywhere and no website. I doubt you'll get any questions before that is resolved.

**Comment by andvgal** [comment]
@sindresorhus please carefully (re-?)read the short AMA page and feel free to ask the questions in the AMA itself ;)

**Comment by sindresorhus** [comment]
I'm aware there's an Overview there, but it's too long. Like most users, if I don't understand what something is in a few seconds, I'll just leave. You should have a couple of sentences in the AMA readme that succinctly explain what FutoIn is, without having to hunt for the information or read lots of text.

**Comment by andvgal** [comment]
There is a generic description of the umbrella FutoIn project: "Open Source concepts, tools and reference implementations.", there is more detailed "Intro" as the first item in the Overview.

Each sub-project does have own description, e.g. https://github.com/futoin/cid-tool - "CID - FutoIn Continuous Integration & Delivery Tool".

Standalone website is obviously pending time dedication.

if you do not want to add one by any personal reasons, no problem.

**Comment by sindresorhus** [comment]
I'm gonna close this as it's still too vague.

**Pull request closed without merging**
