### PR TITLE
I'd like to propose my ama for this list.

### PR DESCRIPTION
**Pull request by khalillechelt**
As per [your encouragement](https://twitter.com/sindresorhus/status/657134662008074240) :smile:

### CODE REVIEW

**Comment by kevva** [comment]
Welcome yo :).

**Comment by khalillechelt** [comment]
thanks :)

**Comment by sindresorhus** [comment]
Welcome friend!

Would be cool if you could ask some questions on the other AMAs in the list (not my AMA). I think AMAs are a great opportunity to learn from each other. Asking a question is also a good way to encourage receiving one ;)

For inspiration of what to ask, you could take a look at the questions in some other AMAs, like:
https://github.com/passy/ama/issues?q=
https://github.com/sebmck/ama/issues?q=
https://github.com/wesbos/ama/issues?q=

**Comment by khalillechelt** [comment]
Hey @sindresorhus thanks for the reminder :)

**Pull request merged**
