### PR TITLE
add Justin Miller to amas

### PR DESCRIPTION
**Pull request by incanus**

### CODE REVIEW

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/amas/blob/master/contributing.md

**Comment by sindresorhus** [comment]
Closing for lack of response from OP.

**Comment by incanus** [comment]
Can you help clarify which contribution rule I am not following? I did check that link before opening the PR.

**Comment by arthurvr** [comment]
This one:

> Start the bio with a capital and end with a full stop/period.

**Comment by arthurvr** [comment]
There's also a merge conflict.

**Comment by incanus** [comment]
Ok, I think I addressed the above in https://github.com/incanus/amas/commit/a51506d5e7b6c7d8cc9070d305018ee35f395b2c based off of d0b3db2ea185f1b6d8f73f99e00e554f9d1a5c90. Thanks for the clarification.

**Comment by arthurvr** [comment]
Welcome!

**Comment by sindresorhus** [comment]
Hey. Want to ask you a favor. Would be cool if you could ask some questions on the other AMAs in the list (not my AMA). I think AMAs are a great opportunity to learn from each other. Asking a question is also a good way to encourage receiving one ;)

For inspiration of what to ask, you could take a look at the questions in some other AMAs, like:
https://github.com/passy/ama/issues?q=
https://github.com/sebmck/ama/issues?q=
https://github.com/wesbos/ama/issues?q=
https://github.com/sindresorhus/ama/issues?q=

**Pull request merged**
