### PR TITLE
Add Joe Ferguson

### PR DESCRIPTION
**Pull request by svpernova09**

### CODE REVIEW

**Comment by sindresorhus** [comment]
You forked the wrong repo. Use the link in the guide: https://github.com/sindresorhus/amas/blob/master/create-ama.md

**Comment by svpernova09** [comment]
The links there point to the amas repo? I forked the ama repo here: https://github.com/svpernova09/ama but had to fork the amas to send a PR to add to the list in this repo? 

Confused because the AMA repo doesn't have the list?

**Comment by sindresorhus** [comment]
In this PR you're linking to the forked `amas` repo instead of your `ama`. Just update this PR with the correct link.

**Comment by svpernova09** [comment]
Gotcha, sorry. All fixed now

**Comment by sindresorhus** [comment]
Hey. Want to ask you a favor. Would be cool if you could ask some questions on the other AMAs in the list (not my AMA). I think AMAs are a great opportunity to learn from each other. Asking a question is also a good way to encourage receiving one ;)

For inspiration of what to ask, you could take a look at the questions in some other AMAs, like:
https://github.com/passy/ama/issues?q=
https://github.com/sebmck/ama/issues?q=
https://github.com/wesbos/ama/issues?q=
https://github.com/sindresorhus/ama/issues?q=

**Pull request closed without merging**
