### PR TITLE
Add Jim Lesperance

### PR DESCRIPTION
**Pull request by cooljl31**

### CODE REVIEW

**Comment by sindresorhus** [comment]
You added it to the wrong place in the list. You also need to enable the Issues tab on your fork.

**Comment by cooljl31** [comment]
👍 I have activated this option 😄

**Comment by sindresorhus** [comment]
You have not.

**Comment by cooljl31** [comment]
Which option you want me to activate?
Screenshot 2019-07-01 at 12 00 44

**Comment by sindresorhus** [comment]
You have probably enabled it on the wrong repo.

**Comment by cooljl31** [comment]
I activate it for https://github.com/cooljl31/ama. Is this what you mean?

**Comment by sindresorhus** [comment]
Yes

**Pull request merged**
