### PR TITLE
Add Max Stoiber

### PR DESCRIPTION
**Pull request by mxstbr**
:tada:

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by mxstbr** [comment]
Fixed, sorry about that!

**Comment by sindresorhus** [comment]
No worries. You probably forked right before https://github.com/sindresorhus/amas/commit/7a23d97b6777b94ed25408abdb0c7c2be1b5d8a9 ;)

**Comment by sindresorhus** [comment]
Welcome! :)

Would be cool if you could ask some questions on the other AMAs in the list (not my AMA). Especially the ones closer to the bottom of the list. I think AMAs are a great opportunity to learn from each other. Asking a question is also a good way to encourage receiving one ;)

For inspiration of what to ask, you could take a look at the questions in some other AMAs, like:
https://github.com/passy/ama/issues?q=
https://github.com/sebmck/ama/issues?q=
https://github.com/wesbos/ama/issues?q=

**Pull request merged**
