### PR TITLE
Added Richard Littauer AMA link

### PR DESCRIPTION
**Pull request by RichardLitt**

### CODE REVIEW

**Comment by sindresorhus** [comment]
`sometime` => `sometimes`?

**Comment by RichardLitt** [comment]
Nah, that's grammatical. It's the rarer case where `sometime` is an adjective and not an adverb. http://dictionary.reference.com/browse/sometime

**Comment by sindresorhus** [comment]
Alright. `sometime` just sounds to me like it's sometime in the future, not sometime as occasionally.

**Comment by RichardLitt** [comment]
Huh. That's a cool interpretation. :) Thanks!

**Comment by sindresorhus** [comment]
Hey. Want to ask you a favor. Would be cool if you could ask some questions on the other AMAs in the list (not my AMA). I think AMAs are a great opportunity to learn from each other. Asking a question is also a good way to encourage receiving one ;)

For inspiration of what to ask, you could take a look at the questions in some other AMAs, like:
https://github.com/passy/ama/issues?q=
https://github.com/sebmck/ama/issues?q=
https://github.com/wesbos/ama/issues?q=
https://github.com/sindresorhus/ama/issues?q=

**Comment by RichardLitt** [comment]
Done! <3

**Comment by RichardLitt** [comment]
Will do more.

**Pull request merged**
