### PR TITLE
Add Praveen Kumar & 404 AMA Cleanup.

### PR DESCRIPTION
**Pull request by praveenscience**
* Removed non-existing Arthur Verschaeve's AMA.
* Removed non-existing Jesse cogollo's AMA.
* Added my (Praveen Kumar's) AMA.

### CODE REVIEW

**Comment by praveenscience** [comment]
@sindresorhus Check out my creative AMA. 😄

**Comment by sindresorhus** [comment]
Please read https://github.com/sindresorhus/amas/blob/master/contributing.md

**Comment by praveenscience** [comment]
@sindresorhus Can you clarify?

- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] A link back to this list from your readme, so users can discover more AMAs, would be appreciated.
- [ ] Make an individual pull request for each suggestion. - **Is this the one?**
- [x] Titles should be [capitalized](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html).
- [x] Use the following format: `[Name](link) - Bio.`
- [ ] Link additions should be added to the bottom of the relevant category. - **Is this failed?**
- [x] New categories or improvements to the existing categorization are welcome.
- [x] Start the bio with a capital and end with a full stop/period.
- [x] Check your spelling and grammar.
- [x] Make sure your text editor is set to remove trailing whitespace.
- [x] The pull request and commit should have a useful title. Example: `Add Sindre Sorhus`

**Comment by praveenscience** [comment]
@sindresorhus I would be happy if you could explain what's not there. :(

**Pull request closed without merging**
