### PR TITLE
Add Andy AMA to list

### PR DESCRIPTION
**Pull request by lambtron**

### CODE REVIEW

**Comment by arthurvr** [comment]
Can you fix the merge conflict?

**Comment by lambtron** [comment]
Let me take a look!!

**Comment by lambtron** [comment]
I'm not sure if i can see the merge conflict, strangely. I only made one change and it was to the readme.md file, so i'm not sure what the merge conflict might be. Any ideas?

**Comment by arthurvr** [comment]
I did it for you. `git rebase -i` and you'd have seen what it was :wink:

**Comment by lambtron** [comment]
Haha, thanks!!

**Comment by sindresorhus** [comment]
Want to ask you a favor. Would be cool if you could ask some questions on the other AMAs in the list (not my AMA). I think AMAs are a great opportunity to learn from each other. Asking a question is also a good way to encourage receiving one ;)

For inspiration of what to ask, you could take a look at the questions in some other AMAs, like:
https://github.com/passy/ama/issues?q=
https://github.com/sebmck/ama/issues?q=
https://github.com/wesbos/ama/issues?q=
https://github.com/sindresorhus/ama/issues?q=

**Pull request closed without merging**
