### PR TITLE
Adding Blain

### PR DESCRIPTION
**Pull request by blainsmith**

### CODE REVIEW

**Comment by arthurvr** [comment]
Yay!

**Comment by arthurvr** [comment]
You need to enable the issues in your repo ;)

**Comment by blainsmith** [comment]
Weird. I thought they were on by default. They are on now. :wink:

**Comment by sindresorhus** [comment]
Hey. Want to ask you a favor. Would be cool if you could ask some questions on the other AMAs in the list (not my AMA). I think AMAs are a great opportunity to learn from each other. Asking a question is also a good way to encourage receiving one ;)

For inspiration of what to ask, you could take a look at the questions in some other AMAs, like:
https://github.com/passy/ama/issues?q=
https://github.com/sebmck/ama/issues?q=
https://github.com/wesbos/ama/issues?q=
https://github.com/sindresorhus/ama/issues?q=

**Comment by blainsmith** [comment]
Thanks for the ping. I meant to go through some this past week, but got distracted. :+1:

**Pull request merged**
